### ISSUE TITLE
Switch to tab-bar icons?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookAndroid#102]
Looks like setting the text to "" displays the icons.  I think we can do this.  Need right size icons.

**Comment by ericberman** [comment]
Need selected and un-selected states at: 32x32, 48x48, 64x64, and 96x96.
Icons are: new flight, aircraft, recents, currency, totals, visited airports, training, and options (profile).  
This is the same set as for iOS, which are great;  the only differences are the resolutions and the need for both a selected and an unselected state (i.e., so that you can tell which tab is active).  One thought is to use color for active?

**Comment by zularizal** [comment]
Okay, I'll make it for you, maybe with color can make it easy to differentiate active and inactive.

**Comment by zularizal** [comment]
Sorry eric for late response, I've made two types of icons as you need, the first one is active for blue and inactive for gray.

If you can, can you change the look of the android theme looks as bright as the iOS Look, because I think it looks good if with light colors (white theme).

[ANDROID ICON.zip](https://github.com/ericberman/MyFlightbookAndroid/files/2152815/ANDROID.ICON.zip)

**Comment by ericberman** [comment]
Look good - thanks!
