### ISSUE TITLE
Move aircraft update to background when possible

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookAndroid#237]
Having a slow connection disables the UI for long durations when update is happening even when not needing it to view or edit a flight 
![Screenshot_20210812-080717_MyFlightbook](https://user-images.githubusercontent.com/1769078/129405764-5fcaa4c7-1b0d-40d6-9e9a-8231ce49f93e.jpg)

**Comment by ericberman** [comment]
I do in fact perform the actual download in the background, but I can't do anything else until your aircraft are downloaded at least once, so this is by design.  The code more or less everywhere assumes that any flight can tie to an aircraft. 

Suggest you also consider doing pack-and-go while on a fast connection.

**Comment by ericberman** [comment]
I've coded background for pack-and-go
