### ISSUE TITLE
RTL UI issues 

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookAndroid#238]
![Screenshot_20210815-080820_MyFlightbook](https://user-images.githubusercontent.com/1769078/129467817-ef667d5a-90e4-48e9-b505-1ab97d961434.jpg)
![Screenshot_20210815-080834_MyFlightbook](https://user-images.githubusercontent.com/1769078/129467818-3a632b2f-96e2-4e5e-9747-2dbc3b0dea2a.jpg)

**Comment by ericberman** [comment]
Can you clarify what the issues are here?  In the first screenshot, it looks like the Flight Detail dropdown is misaligned, but everything else looks like it's switching from LTR to RTL correctly - am I missing anything?

Not quite sure what the issue is in the 2nd image.

**Comment by zartom** [comment]
In both images, the labels are on the right, and fields are on the left - look at the semicolons for example. It doesn't make much sense like this when not in an actual RTL language.

**Comment by zartom** [comment]
Also flight details field + "Med" text value are not aligned to any edge properly

**Comment by ericberman** [comment]
Gotcha thanks. Yeah it looked strange to Mayeye to, but this is all being done automatically by android I wasn't quite sure what the convention was for displaying English text when using a right to left region￼. I don't have anything to do with reversing.  Play, since that's all in English, I think it's weird to have the checkboxes on the right as well. I just thought that that was the convention. 

I'm going to have to do some research to figure this one out. At least on the web, things tend to be pretty smart about going right to left for Hebrew or Arabic, and left to right for Latin languages and more importantly doing it dynamically based on the actual text involved, not based on your region. And this might just be android being stupid and not recognizing that all of the text is still in English aince I don't have a Hebrew translation.￼￼

**Comment by ericberman** [comment]
<img width="414" alt="Screen Shot 2021-09-14 at 3 46 18 PM" src="https://user-images.githubusercontent.com/16455286/133343725-15fbb500-d21e-40ac-8ce7-d66b36933c65.png">
Does this look weird or is it OK?

**Comment by ericberman** [comment]
So the issue is that I want to have something like this:
| | |
|---|---|
| label| control |
| label | control|

That is, the labels are all aligned vertically with each other and the controls are all aligned horizontally with each other, and each label is vertically aligned with its associated with control (for effective and easy-to-scan) layout.

So in English, it should be
 LABEL Control
and in Hebrew it should be (if Google Translate is doing this correctly)
 בקרת תוויות. 
I.e.,
lortnoC <- labeL

The issue is that in a right-to-left region, Android is (probably correctly) making the column order RTL, even though the columns contain English text due to the lack of a Hebrew (or Arabic) translation.

So in the screenshot above, I've explicitly forced the column order to be LTR.  Obviously, that breaks if I ever do an RTL translation, but if I ever do that it's both easy to back out the "Force LTR" flag, which will be no longer necessary.

Thoughts?
