### ISSUE TITLE
New Logo For My Flight Book Android

### ISSUE THREAD

**Issue by zularizal** [ericberman/MyFlightbookAndroid#77]
Hello @ericberman  , I want contribute to My Flight Book, so i designed a new logo for My Flight Book and it's free. I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

You can choose the color you like. 

![plane](https://user-images.githubusercontent.com/38547278/39226519-32aa8976-487d-11e8-8fd7-58c818ed5a05.png)

**Comment by ericberman** [comment]
Hi.  Interested in helping with a broader artistic redesign?  Could use some real design skills, and if I were to update the logo, I think it would need to be in concert with a broader visual refresh.

These logos look good.  I would need a whole slew of different sizes, though, because it’s iOS and Web, iTunes and Google Play.  The set of dimensions I currently have to support is pretty astronomical, actually:

Icons (i.e., what is today just the square magenta airplane, not where it is the “t” in “MyFlightbook”):
Android – 144x144, 96x96, 72x72, 48x48, 36x36
iOS: 152x152, 144x144, 120x120, 114x114, 100x100, 76x76, 72x72, 64x64, 58x58, 57x57, 50x50, 32x32, 29x29, 15x16
iOS Apple Watch: 24x24, 27.5x27.5, 29x29, 55x55, 58x58, 87x87, 80x80, 88x88,172x172, 196x196, 98x98, 120x120, 180x180
iOS Splash Screen (i.e., including the full word “MyFlightbook”, on black background):320x480, 640x960, 640x1136, 1024x748, 2048x1496, 1024x768,2048x1536, 768x1004, 1536x2008,768x1024, 1536x2048,768x1004
Website: 1024x1024, 15x16, 29x29,20x20, 57x57
iTunes/GooglePlay/Website (full word, white background): 512x512 (transparent and opaque), 1024x1024 (transparent and opaque), 120x120 (transparent and opaque).

Happy to chat about a broader visual refresh…

**Comment by zularizal** [comment]
Hi @ericberman , I've uploaded the logo file and icons you requested to drive, please check
https://drive.google.com/open?id=1kiwvtML_UnlKR3ENPZ34LX7B7MVWAcbJ

If necessary change, please let me know. If not, I'll send a pull request to add that logo to the readme.

**Comment by ericberman** [comment]
Wow, these look really good!  Up for helping with a broader UI visual refresh to match the new color?  iOS and Android apps look like vanilla iOS and Android, so I don’t think there’s a ton needed there, but the tabs and yellow background on the website are getting dated and I think clash with the colors in this.

I’ll try to put together a sample website you can hit with these in the next few days, can take a look…

**Comment by zularizal** [comment]
All right, I'll wait, if you need to change, you can contact me in this issues

**Comment by ericberman** [comment]
OK, am in the middle of trying to push out an update to the mobile apps; after that, let me try putting this on the website and let's take a look at that holistically.  I'd love a refresh on that, branding is a piece of it.  Thanks!

**Comment by ericberman** [comment]
Hi, taking a brief look at this now.  I forgot a few other dimensions (there are just so many!) for the web.  4 with the word "MyFlightbook": 198x67 (transparent background and white background), 201x67 (transparent background), and 100x33 (transparent); some of these may be obsolete... also a 48x48 .ico file (transparent background).

Anyhow, here is what I'm talking about w.r.t. the "holistic" branding/theming: 
![image](https://user-images.githubusercontent.com/16455286/39409645-95bf2394-4b9f-11e8-955a-0ebef8cf7692.png)

So a few things on the design here:
 * The yellow that I currently have is already ugly, I don't think it's improved by the blue themed logo.  I've been thinking that I actually want to migrate away from the yellow anyhow.  I've been able to do that on the main [logbook page](https://developer.myflightbook.com/logbook/Member/LogbookNew.aspx), but that model breaks down for other parts of the site.
 * The gray tabs look OK with the blue, but the whole tab model is about 20 years out of date.  I need a new, more modern primary/secondary nav model.  One possibility is to go with the mobile UI model (all white background too) - click on "Mobile Access" at the bottom of the page to see what that looks like - but I think the visuals of *that* can also be greatly improved, both in terms of colors/fonts/etc., but also in terms of raw layout.  E.g., my primary nav on the site is currently tabs on top for primary nav, secondary nav down the left side, a "top" form with the hideous yellow background (where data entry is performed), and a "bottom" form (white background) for any resulting content to be displayed.  In the screenshot above you can see each of these elements, with just a tiny bit of the bottom form displayed.  If you go into the mobile mode, though, there are two primary changes: (a) it's all white background, and (b) the secondary nav moves to the top row, so it becomes effectively a second row of tabs.  Bleah.
 * The blue in the logos you provided is a strong element, it should be reinforced by use of that color elsewhere in the theme for the site - it should be in the primary/secondary nav model (currently the tabs), it should be in things like border edges, where there should be non-white backgrounds the background should complement the logo colors.  Even little things like the heading fonts (see the image above) currently clash with the proposed logo colors and thus should change (and the choice of font should, if possible, be complementary with the logo font).  That's the sort of advice I'd love to get from you.

So I greatly appreciate your help on this.  The site has always been much more function over form because I don't have a design bone in my body.  I can code it, I can do the CSS, but I'd love some wireframes that show a better, more modern design layout.

**Comment by zularizal** [comment]
Hi, I've added some other dimensions to folder "Web" in drive.

I like your web, but I do not understand about web design, but I think you should upgrade your web to look more modern.

I change the color blue to look matching with other colors?
How do you think?

![web](https://user-images.githubusercontent.com/38547278/39412046-31bc639c-4c40-11e8-915a-f856ce31427c.png)

**Comment by ericberman** [comment]
The blues are still different, and it still has my old horrible yellow background and tabs.  You are absolutely right that I need to update the web to look more modern - that's what I'm hoping you can help with.  I think doing a new branding (i.e., logo) doesn't just make sense in the broader branding context, I actually think it would be necessary in doing so.  

I have all three platforms (iOS, Android, and Web), I can't change just one.  A new logo needs to work on all of them, which means doing precisely the upgrade that you and I agree about on the web...which requires a new more modern look on the web. 

Would love any help you can offer there...

**Comment by zularizal** [comment]
I want to help you, but i can not about coding, I can only get a bit about design.

**Comment by ericberman** [comment]
I can do all the coding.  If you can draw wireframes for me (i.e., sample screenshots, without worrying about the specific content), I can code it.

**Comment by zularizal** [comment]
Okay, I'll give it a try, from where I first have to design. Web or smartphone?

**Comment by ericberman** [comment]
Web.  The smartphones have very light branding, they’re pretty vanilla iOS or Android UI, so the logo change is easier there.  (If it were simply android or simply iOS, I’d just migrate to what you’ve done.  But I need all three to have consistent branding).

Thanks

**Comment by zularizal** [comment]
Okay, Give me time, I'll try to make it

**Comment by ericberman** [comment]
I’m liking it!  This may be the basis of something I can work with!

Couple of questions/notes:

  1.  The icons for logbook/aircraft/etc. would need to be adapted for iOS.  (Another pilot has sent me some screenshots for visual redesign on iOS; may be able to merge the two).  I like the icons below.  iOS has some weird rules about size/color, but I think that’s getting way ahead of ourselves right now.
  2.  I like the tabs!  (I have one more tab: admin, but obviously only I get to see that.  Doesn’t need an icon…)  Do you have those in large/small I can try out?
  3.  Can you send me RGB values for the blues and the rounded borders?  Font names/sizes?
  4.  Thoughts about how secondary nav would work?  Direct access remains via drop-down menu from the tabs?  But, for example, if I click on “Training”, how do I navigate between 8710 form and ratings progress and instructors?  Right now I have a sidebar down the left, would love your thoughts about how to incorporate that!
  5.  I know below is a wireframe, but you have what appears to be an image slideshow thing below the “about” stuff; I’m curious what your thoughts were about the image

Thanks!

--Eric

**Comment by zularizal** [comment]
Hi, I think there are some drawbacks on the logo I have made before. So I redesigned the logo, what do you think?

And I have re-uploaded iOS and other icon files, you can check in this link.

https://drive.google.com/open?id=1kiwvtML_UnlKR3ENPZ34LX7B7MVWAcbJ

![logo design](https://user-images.githubusercontent.com/38547278/40276934-1a8ed9ba-5c40-11e8-9377-6c87feccf8ed.png)

1. I have added the color code details and the font name.

2. To adjust to the logo color, then I change the background color of the web.

3. The slide serves to display the list of aircraft like on your web. If you do not have to delete it.

4. That is the dropdown form I think, what do you think?

![webpage](https://user-images.githubusercontent.com/38547278/40276935-1ae00682-5c40-11e8-95ab-1374d60b771f.png)

**Comment by ericberman** [comment]
I’m liking it.  I think this is something I can play with.  May take me a little bit, but maybe I can get a test site going this week that implements this – then we can play and see what we think.

Thanks

**Comment by ericberman** [comment]
By the way – we should probably take this to email.  Can you contact me on email at myflightbook – at – gmail.com?

Thanks.  Should have something (very) simple to play with shortly.  Fortunately, I have a whole “branding” architecture that allows multiple skins on the site; unfortunately, since I’ve only ever had one brand, there are places where I will need to change code or make things configurable entirely via CSS.  However, I think it’s worth doing many of these changes even before a switch-over (i.e., even in the current look-and-feel).

Thanks

**Comment by zularizal** [comment]
Sure

**Comment by zularizal** [comment]
Hi eric, what about your website?
I have tried the feature contact us, do you get my message?

What cms do you use on this website?

**Comment by ericberman** [comment]
I love the new icons.  Implemented in iOS, web, and android.
